title: DXD Jekyll
author: Carlos Soares
email: carlossoares.cg@gmail.com
description: > # this means to ignore newlines until "exclude"
 This website is being created as an exercise for DXD post graduation.

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%b %-d, %Y"

# generate social links in footer
social_links:
  twitter: carlosmmsoares
  github:  carlosmms
  # facebook:
